title: Austin Bay
name: Austin Bay
color_scheme: auto
url: "https://austinjbay.com"

header:
  header__title: Austin Bay

author:
  author__name: Austin Bay
  author__bio: Growth Product
  author__avatar: /assets/images/Headshot2.jpg

hero:
  hero__title: Building products that become part of everyday life
  hero__description: "The best consumer SaaS products don't just compete for attention.
They earn a place in people's routines."
  
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/austin-bay-2763a918/"}
- {icon: "ion-logo-twitter", link: "https://x.com/austinjbay"}
- {icon: "ion-logo-github", link: "https://github.com/austinjbay"}

google-analytics: G-C3NW59QVPZ
permalink: /:title

plugins:
  - jekyll-paginate
  - jekyll-sitemap
